#!/usr/bin/php
<?php

$session = getenv( 'GIST_SESSION' );
if ( empty( $session ) )
	die( 'GIST_SESSION was empty' . "\n" );

$gists = array();
$has_next_page = false;
$page = 1;

$opts = array(
	'http' => array(
		'method' => 'GET',
		'header' => 'Cookie: _gh_sess=' . $session . '; tracker=direct',
	)
);

$context = stream_context_create( $opts );

do {
	echo "Fetching page $page\n";
	$content = file_get_contents( 'https://gist.github.com/mine?page=' . $page, false, $context );
	if ( strpos( $content, '<div class="userbox">' ) === false )
		die( 'Bad session value' . "\n" );
	preg_match_all( '#<span><a href="/([0-9a-f]{20})">gist: \1</a></span>#', $content, $matches, PREG_PATTERN_ORDER );
	$gists = array_merge( $gists, $matches[1] );
	$page++;
	$has_next_page = strpos( $content, '<a href="/mine?page=' . $page . '">Older &raquo;</a>' ) !== false;
} while( $has_next_page );

echo "Processing gists\n";

foreach ( $gists as $gist ) {
	echo "$gist\n";
	$command = 'if [ ! -d ' . $gist . ' ]; then git clone git@gist.github.com:' . $gist . '.git ; else git --git-dir=' . $gist . '/.git pull; fi';
	passthru( $command );
}